name: CI/CD to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nodejs-backend:latest backend/

      # Push Docker image to Google Container Registry
      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nodejs-backend:latest

      # Terraform Init
      - name: Terraform Init
        run: |
          terraform -chdir=terraform init

      # Terraform Apply
      - name: Terraform Apply
        run: |
          terraform -chdir=terraform apply -auto-approve
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: us-central1
          TF_VAR_container_image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nodejs-backend:latest
