name: CI/CD to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nodejs-backend:latest backend/

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      # Push Docker image to Google Container Registry
      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nodejs-backend:latest

      # Terraform Init
      - name: Terraform Init
        run: |
          terraform -chdir=terraform init

      # Terraform Apply
      - name: Terraform Apply
        run: |
          terraform -chdir=terraform apply -auto-approve
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: us-central1
          TF_VAR_container_image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nodejs-backend:latest
