name: CI/CD to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3
          

      # Setup Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Install Docker via the system's package manager (apt-get for Ubuntu)
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      # Authenticate Docker to GCR (Google Container Registry)
      - name: Authenticate Docker to GCR
        run: |
          gcloud auth configure-docker


      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nodejs-backend:latest backend/

      - name: Authenticate Docker to GCR
        run: echo "${{ secrets.GCP_CREDENTIALS }}" | docker login -u _json_key --password-stdin https://gcr.io

      # Push Docker image to Google Container Registry
      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nodejs-backend:latest

      # Terraform Init
      - name: Terraform Init
        run: |
          terraform -chdir=terraform init

      # Terraform Apply
      - name: Terraform Apply
        run: |
          terraform -chdir=terraform apply -auto-approve
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: us-central1
          TF_VAR_container_image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nodejs-backend:latest
